### ISSUE TITLE
正常操作，服务端有如下错误

### ISSUE THREAD

**Issue by keyqq** [yuanfengyun/mj_server#1]
[:00000001] LAUNCH logger 
[:00000002] LAUNCH snlua bootstrap
[:00000003] LAUNCH snlua launcher
[:00000004] LAUNCH snlua cdummy
[:00000005] LAUNCH harbor 0 4
[:00000006] LAUNCH snlua datacenterd
[:00000007] LAUNCH snlua service_mgr
[:00000008] LAUNCH snlua main
[:00000009] LAUNCH snlua debug_console 8000
[:00000009] Start debug console at 127.0.0.1:8000
[:0000000a] LAUNCH snlua login
[:0000000a] login booted...
[:0000000a] socket: auth failed ./skynet/lualib/mongo.lua:96: assertion failed!
[:0000000a] Connect to 127.0.0.1:27017 failed (nil)
[:0000000a] lua call [0 to :a : 0 msgsz = 24] error : ./skynet/lualib/skynet.lua:531: ./skynet/lualib/skynet.lua:156: [Error: socket]
stack traceback:
	[C]: in function 'error'
	./skynet/lualib/socketchannel.lua:332: in function <./skynet/lualib/socketchannel.lua:306>
	(...tail calls...)
	./skynet/lualib/mongo.lua:171: in function 'mongo.client'
	./lualib/mongolib.lua:16: in function 'mongolib.connect'
	./service/login/account_mgr.lua:20: in function 'account_mgr.init'
	./service/login/main.lua:9: in local 'f'
	./service/login/main.lua:25: in upvalue 'f'
	./skynet/lualib/skynet.lua:111: in function <./skynet/lualib/skynet.lua:105>
stack traceback:
	[C]: in function 'assert'
	./skynet/lualib/skynet.lua:531: in function 'skynet.manager.dispatch_message'
[:00000008] init service failed: ./skynet/lualib/skynet.lua:388: call failed
stack traceback:
	[C]: in function 'error'
	./skynet/lualib/skynet.lua:388: in upvalue 'yield_call'
	./skynet/lualib/skynet.lua:399: in function 'skynet.call'
	./service/main.lua:8: in local 'start'
	./skynet/lualib/skynet.lua:626: in function <./skynet/lualib/skynet.lua:623>
	[C]: in function 'xpcall'
	./skynet/lualib/skynet.lua:630: in function 'skynet.pcall'
	./skynet/lualib/skynet.lua:634: in function 'skynet.init_service'
	./skynet/lualib/skynet.lua:647: in upvalue 'f'
	./skynet/lualib/skynet.lua:106: in function <./skynet/lualib/skynet.lua:105>
[:00000008] KILL self
[:00000002] KILL self

**Comment by yuanfengyun** [comment]
小伙，你安装了mogodb了么？

**Comment by keyqq** [comment]
感谢大佬
