### ISSUE TITLE
auto_table_with_eye.lua关于胡牌疑问

### ISSUE THREAD

**Issue by PolarSnow** [yuanfengyun/mj_server#11]
auto_table_with_eye.lua
玩家玩麻将的时候可能会出现只有一对万子而没有其他万子的情况。这种情况不是应该归类到auto_table_with_eye.lua么。[2] = true

**Comment by PolarSnow** [comment]
另外doc里面说的3n+2的n范围是[0-4]吧

**Comment by yuanfengyun** [comment]
对

**Comment by yuanfengyun** [comment]
lua更新了一版。

**Comment by PolarSnow** [comment]
现在auto_table_with_eye.lua还没有 [2] = true，麻烦加上❤

**Comment by yuanfengyun** [comment]
最新版的在https://github.com/yuanfengyun/qipai

**Comment by PolarSnow** [comment]
谢谢
