### ISSUE TITLE
麻将算法问题:只要是同花色1到9都有就不会检测

### ISSUE THREAD

**Issue by zhangshiqian1214** [yuanfengyun/mj_server#2]
1万2万3万 4万5万6万 7万7万 8万9万  4筒4筒4筒
算法判断是能胡的, 其实不应该胡
local t = {
        1,1,1,   1,1,1,   2,1,1,
        0,0,0,   3,0,0,   0,0,0,
        0,0,0,   0,0,0,   0,0,0,
        0,0,0,0, 0,0,0
    }
    if not hulib.get_hu_info(t) then
        print("测试失败")
    else
        print("测试成功")
    end

----------------结果------------]
测试成功
测试	1	次,耗时	0
[Finished in 0.1s]

**Comment by zhangshiqian1214** [comment]
修改base/hulib.lua 的 M._check_color_chi() 里面加上一个判断就可以了

`lua`
function M.check_color_chi(cards, cfg, info)
    local tbl = {}
    for i = cfg.min, cfg.max do
        repeat
            local count = cards[i]
            if count > 0 then
                table.insert(tbl, count)
            else
                if #tbl == 0 then
                    break
                end
                print("tbl=", #tbl)
                if not M.check_sub(tbl, info) then
                    return false
                end
                tbl = {}
            end
        until(true)
    end

    if #tbl ~= 0 and not M.check_sub(tbl, info) then
        tbl = nil
        return false
    end
    tbl = nil
    return true
end

**Comment by yuanfengyun** [comment]
多谢了。
