### ISSUE TITLE
请问下，mjlib/base/auto_table.lua 的数据是如何生成的？

### ISSUE THREAD

**Issue by ksingeryu** [yuanfengyun/mj_server#7]
如题，请教。

**Comment by yuanfengyun** [comment]
执行 lua mjlib/base/gen_auto_table.lua

**Comment by ksingeryu** [comment]
目前源码auto_table.lua是自带数据，所以执行了肯定有数据。
如果不带数据呢？我看了gen_auto_table.lua代码，貌似没有新增数据到auto_table.lua里面。
gen_auto_table.lua能否注释下，看不太明白，麻烦楼主。

**Comment by yuanfengyun** [comment]
lua功底不够啊。

**Comment by ksingeryu** [comment]
是啊，新手学习中，望指点下。

**Comment by yuanfengyun** [comment]
所有代码都在那个目录，你自己慢慢看。这个帮不了你。

**Comment by ksingeryu** [comment]
ok，我再多看看。
